import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {LocalPlaywrightDriver} from '../worker/local-playwright-driver.mjs';
const {chromium}=await import(process.env.SENTINEL_TEST_PLAYWRIGHT_MODULE||'playwright');
let browser,page,driver;
before(async()=>{browser=await chromium.launch({headless:true,...(process.env.SENTINEL_TEST_BROWSER_PATH?{executablePath:process.env.SENTINEL_TEST_BROWSER_PATH}:{})});page=await browser.newPage({viewport:{width:1366,height:900}});driver=new LocalPlaywrightDriver({dataDir:'worker/data/browser-test'});driver.session=async()=>({page,background:false});});
after(async()=>{await browser?.close()});
const data=(patch={})=>({asset:'TEST/USD',state:'running',side:'BUY',confidence:85,strategy:'trend',durationMs:60000,liveAgeMs:0,analysisAgeMs:0,minConfidence:70,metrics:{sourceCandles:140,shortModel:{ready:true,callScore:85,putScore:15}},quality:{entryReady:true,entrySide:'BUY',technicalBuy:85,technicalSell:15},operationalSignal:{side:'CALL',state:'ENTRADA',ready:true,strength:85,trigger:101,invalidation:98,reason:'Gatilho confirmado.',expiration:{detected:true,match:true,brokerMs:60000}},...patch});
const signal=()=>page.locator('[data-sentinel-role="main-signal"]');
async function render(patch={}){await driver.updateOverlay('iq_option',data(patch));}
test('one principal CALL and technical points, without the historical accuracy card',async()=>{await page.setContent('<html><body><h1>Broker fixture</h1></body></html>');await render();const text=await signal().innerText();assert.match(text,/CALL/);assert.match(text,/85\/100/);assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),0);assert.doesNotMatch(await page.locator('#sentinel-trading-overlay').innerText(),/ACERTO HISTÓRICO/);});
test('analytical details open on demand and stay open across updates',async()=>{await page.locator('[data-sentinel-toggle="analysis"]').click();assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),1);await render({analysisAgeMs:100});assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),1);await page.locator('[data-sentinel-toggle="analysis"]').click();assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),0);});
test('stale analysis hides an earlier CALL',async()=>{await render({analysisAgeMs:10000});assert.match(await signal().innerText(),/SINCRONIZANDO/);assert.doesNotMatch(await signal().innerText(),/Gatilho confirmado/);assert.doesNotMatch(await signal().innerText(),/\nCALL\n/);});
test('pause and master freeze hide actionable signals',async()=>{await render({state:'paused'});assert.match(await signal().innerText(),/PAUSADO/);await render({masterFrozen:true});assert.match(await signal().innerText(),/SINCRONIZANDO/);});
test('the main direction follows the operational PUT rather than the primary BUY',async()=>{await render({operationalSignal:{...data().operationalSignal,side:'PUT'}});assert.match(await signal().innerText(),/\nPUT\n/);});
test('a focused strategy selector survives a live update',async()=>{await render();const select=page.locator('[data-sentinel-setting="strategy"]');await select.focus();await select.evaluate(el=>el.dataset.testMarker='kept');await render({analysisAgeMs:200});assert.equal(await select.getAttribute('data-test-marker'),'kept');await select.evaluate(el=>el.blur());});
test('expiry scanning does not confuse investment value with the duration selector',async()=>{await page.setContent('<html><body><main><div><label>Valor<input name="amount" value="10" style="width:100px;height:30px"></label></div><div><label>Duração<input name="duration" value="1" style="width:100px;height:30px"></label></div><button>CALL</button><button>PUT</button></main></body></html>');const st=driver.state('iq_option');st.uiSymbol=st.symbol='TEST/USD';st.mode='real';await driver.scanExecutionUi('iq_option');assert.equal(st.expirationDurationMs,60000);assert.equal(st.expirationRaw,'1');});
test('a disappearing expiration clears the old verified duration immediately',async()=>{await page.setContent('<html><body><h1>Loading broker</h1></body></html>');await driver.scanExecutionUi('iq_option');assert.equal(driver.state('iq_option').expirationDurationMs,null);assert.equal(driver.state('iq_option').expirationConfidence,0);});
