import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {LocalPlaywrightDriver} from '../worker/local-playwright-driver.mjs';
const {chromium}=await import(process.env.SENTINEL_TEST_PLAYWRIGHT_MODULE||'playwright');
let browser,page,driver;
before(async()=>{browser=await chromium.launch({headless:true,...(process.env.SENTINEL_TEST_BROWSER_PATH?{executablePath:process.env.SENTINEL_TEST_BROWSER_PATH}:{})});page=await browser.newPage({viewport:{width:1366,height:900}});driver=new LocalPlaywrightDriver({dataDir:'worker/data/browser-test'});driver.session=async()=>({page,background:false});});
after(async()=>{await browser?.close()});
const data=(patch={})=>({asset:'TEST/USD',state:'running',side:'BUY',confidence:85,strategy:'trend',durationMs:60000,liveAgeMs:0,analysisAgeMs:0,minConfidence:70,metrics:{sourceCandles:140,shortModel:{ready:true,callScore:85,putScore:15}},quality:{entryReady:true,entrySide:'BUY',technicalBuy:85,technicalSell:15},operationalSignal:{side:'CALL',state:'ENTRADA',ready:true,strength:85,trigger:101,invalidation:98,reason:'Gatilho confirmado.',expiration:{detected:true,match:true,brokerMs:60000}},...patch});
const signal=()=>page.locator('[data-sentinel-role="main-signal"]');
async function render(patch={}){await driver.updateOverlay('iq_option',data(patch));}
test('one principal CALL and technical percentages, without the historical accuracy card',async()=>{await page.setContent('<html><body><h1>Broker fixture</h1></body></html>');await render();const text=await signal().innerText();assert.match(text,/CALL/);assert.match(text,/85%/);assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),0);assert.doesNotMatch(await page.locator('#sentinel-trading-overlay').innerText(),/ACERTO HISTÓRICO/);});
test('analytical details open on demand and stay open across updates',async()=>{await page.locator('[data-sentinel-toggle="analysis"]').click();assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),1);await render({analysisAgeMs:100});assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),1);await page.locator('[data-sentinel-toggle="analysis"]').click();assert.equal(await page.locator('[data-sentinel-role="market-reading"]').count(),0);});
test('stale analysis hides an earlier CALL',async()=>{await render({analysisAgeMs:10000});assert.match(await signal().innerText(),/AGUARDANDO DADOS/);assert.doesNotMatch(await signal().innerText(),/Gatilho confirmado/);assert.doesNotMatch(await signal().innerText(),/\nCALL\n/);});
test('pause and master freeze hide actionable signals',async()=>{await render({state:'paused'});assert.match(await signal().innerText(),/PAUSADO/);await render({masterFrozen:true});assert.match(await signal().innerText(),/AGUARDANDO DADOS/);});
test('the main direction follows the operational PUT rather than the primary BUY',async()=>{await render({operationalSignal:{...data().operationalSignal,side:'PUT'}});assert.match(await signal().innerText(),/\nPUT\n/);});
test('a focused strategy selector survives a live update',async()=>{await render();const select=page.locator('[data-sentinel-setting="strategy"]');await select.focus();await select.evaluate(el=>el.dataset.testMarker='kept');await render({analysisAgeMs:200});assert.equal(await select.getAttribute('data-test-marker'),'kept');await select.evaluate(el=>el.blur());});
test('expiry scanning does not confuse investment value with the duration selector',async()=>{await page.setContent('<html><body><main><div><label>Valor<input name="amount" value="10" style="width:100px;height:30px"></label></div><div><label>Duração<input name="duration" value="1" style="width:100px;height:30px"></label></div><button>CALL</button><button>PUT</button></main></body></html>');const st=driver.state('iq_option');st.uiSymbol=st.symbol='TEST/USD';st.mode='real';await driver.scanExecutionUi('iq_option');assert.equal(st.expirationDurationMs,60000);assert.equal(st.expirationRaw,'1');});
test('a disappearing expiration clears the old verified duration immediately',async()=>{await page.setContent('<html><body><h1>Loading broker</h1></body></html>');await driver.scanExecutionUi('iq_option');assert.equal(driver.state('iq_option').expirationDurationMs,null);assert.equal(driver.state('iq_option').expirationConfidence,0);});

test('CALL and PUT percentages update while the operational state waits',async()=>{await page.setContent('<html><body>Broker</body></html>');await render({generalConsensus:{callScore:12,putScore:23},analysisAt:Date.now(),quote:4135,operationalSignal:{...data().operationalSignal,state:'AGUARDAR',ready:false,reason:'Força abaixo do filtro.'}});assert.match(await signal().innerText(),/CALL 12%/);assert.match(await signal().innerText(),/PUT 23%/);await render({generalConsensus:{callScore:19,putScore:31},analysisAt:Date.now(),operationalSignal:{...data().operationalSignal,state:'AGUARDAR',ready:false}});assert.match(await signal().innerText(),/PUT 31%/);assert.doesNotMatch(await signal().innerText(),/pts|\/100/);});
test('broker expiration in an open shadow root is read without enabling execution',async()=>{await page.setContent('<html><body><broker-order></broker-order></body></html>');await page.evaluate(()=>{document.querySelector('broker-order').attachShadow({mode:'open'}).innerHTML='<div class="trade-duration" style="width:120px;height:40px">1 min</div>'});await driver.scanExecutionUi('iq_option');const st=driver.state('iq_option');assert.equal(st.expirationDurationMs,60000);assert.equal(st.executionReady,false);assert.equal(st.executionUi.rootCount,2);});
test('expiration in a broker frame is read while frame buttons do not authorize execution',async()=>{await page.setContent(`<html><body><iframe srcdoc='<div class="expiration-duration" style="width:120px;height:40px">30 s</div><button>CALL</button><button>PUT</button><input name="amount" value="10">'></iframe></body></html>`);await page.frameLocator('iframe').locator('.expiration-duration').waitFor();await driver.scanExecutionUi('iq_option');const st=driver.state('iq_option');assert.equal(st.expirationDurationMs,30000);assert.equal(st.executionUi.buy,false);assert.equal(st.executionReady,false);});
test('Sentinel selectors cannot verify broker expiry',async()=>{await page.setContent('<html><body>Broker</body></html>');await render();await driver.scanExecutionUi('iq_option');const st=driver.state('iq_option');assert.equal(st.expirationDurationMs,null);assert.equal(st.executionUi.expiryCandidateCount,0);});

test('nested custom expiration values and display labels are parsed',async()=>{await page.setContent('<html><body><div class="duration-field"><b>Duração</b><div><span>01:00</span></div></div><select name="duration"><option value="999">1 min</option></select></body></html>');await driver.scanExecutionUi('iq_option');assert.equal(driver.state('iq_option').expirationDurationMs,60000);});

test('changing a selected broker tab resets prices, candles and expiry immediately',async()=>{
 driver.requestMarketData=async()=>false;
 const st=driver.state('iq_option');st.activeMap.set('EURUSDOTC',76);st.activeMap.set('XAUUSD',1912);st.assets.add('EUR/USD OTC');st.assets.add('XAU/USD');
 await page.setContent('<html><body><button role="tab" aria-selected="true">EURUSD-OTC</button><button role="tab" aria-selected="false">XAU/USD</button></body></html>');
 await driver.domSnapshot('iq_option',{fast:true});assert.equal(st.uiSymbol,'EUR/USD OTC');assert.equal(st.activeId,76);
 st.quote=1.1;st.candles=[{from:1,to:2,open:1,close:1,high:1,low:1}];st.quoteHistory=[{price:1.1,ts:Date.now()}];st.expirationDurationMs=60000;
 await page.locator('[role="tab"]').nth(0).evaluate(el=>el.setAttribute('aria-selected','false'));await page.locator('[role="tab"]').nth(1).evaluate(el=>el.setAttribute('aria-selected','true'));
 await driver.domSnapshot('iq_option',{fast:true});assert.equal(st.uiSymbol,'XAU/USD');assert.equal(st.activeId,1912);assert.equal(st.quote,null);assert.equal(st.candles.length,0);assert.equal(st.quoteHistory.length,0);assert.equal(st.expirationDurationMs,null);
 driver.ingest('iq_option',{name:'sendMessage',msg:{name:'get-candles',body:{active_id:76,size:60}}},'page-out');assert.equal(st.uiSymbol,'XAU/USD');assert.equal(st.activeId,1912);
});
test('a late history response from the previous asset cannot populate the new chart',()=>{
 const st=driver.state('iq_option');st.activeId=1912;st.candles=[];st.quote=null;st.candleRequestAssets.set('old-eur',76);
 const candles=[{from:100,to:160,open:1,close:1.1,max:1.2,min:.9}];
 driver.ingest('iq_option',{name:'candles',request_id:'old-eur',msg:{candles}},'direct-in');assert.equal(st.candles.length,0);
 st.candleRequestAssets.set('new-gold',1912);driver.ingest('iq_option',{name:'candles',request_id:'new-gold',msg:{candles}},'direct-in');assert.equal(st.candles.length,1);
});
test('an inactive first tab never becomes the selected asset by position',async()=>{
 await page.setContent('<html><body><button role="tab">EUR/USD OTC</button><button role="tab">XAU/USD</button></body></html>');const st=driver.state('iq_option');st.uiSymbol=st.symbol='XAU/USD';await driver.domSnapshot('iq_option',{fast:true});assert.equal(st.uiSymbol,'XAU/USD');
});
test('a selected tab in an open shadow component is recognized',async()=>{
 await page.setContent('<html><body><broker-tabs></broker-tabs></body></html>');await page.evaluate(()=>document.querySelector('broker-tabs').attachShadow({mode:'open'}).innerHTML='<button role="tab" aria-selected="true">EUR/USD OTC</button><button role="tab" aria-selected="false">XAU/USD</button>');await driver.domSnapshot('iq_option',{fast:true});assert.equal(driver.state('iq_option').uiSymbol,'EUR/USD OTC');
});

test('the selected Gold tab is recognized even when the broker uses its commodity name',async()=>{await page.setContent('<html><body><button role="tab" aria-selected="false">EUR/USD OTC</button><button role="tab" aria-selected="true">Gold Blitz</button></body></html>');await driver.domSnapshot('iq_option',{fast:true});assert.equal(driver.state('iq_option').uiSymbol,'XAU/USD');});

test('bot controls show running, paused, stopped and awaiting-data states',async()=>{await page.setContent('<html><body>Broker</body></html>');await render();assert.match(await page.locator('[data-sentinel-role="bot-status"]').innerText(),/ONLINE · analisando/);assert.equal(await page.locator('[data-sentinel-action="start"]').isDisabled(),true);await render({state:'paused'});assert.match(await page.locator('[data-sentinel-role="bot-status"]').innerText(),/ONLINE · pausado/);assert.match(await page.locator('[data-sentinel-action="start"]').innerText(),/Retomar bot/);await render({state:'stopped'});assert.match(await page.locator('[data-sentinel-role="bot-status"]').innerText(),/bot parado/);await render({liveAgeMs:15000});assert.match(await page.locator('[data-sentinel-role="bot-status"]').innerText(),/aguardando dados/);});
test('a live Agent cannot claim it is analyzing a confirmed chart when asset detection failed',async()=>{await render({assetConfirmed:false});assert.match(await page.locator('[data-sentinel-role="bot-status"]').innerText(),/lendo gráfico/);});
test('loss of Agent updates turns the status offline and disables controls',async()=>{await render({agentHeartbeatAt:Date.now()-4950,agentOnline:true});await page.waitForFunction(()=>document.getElementById('sentinel-trading-overlay-host').shadowRoot.querySelector('[data-sentinel-role="bot-status"]').textContent.includes('OFFLINE'),{},{timeout:2000});assert.equal(await page.locator('[data-sentinel-action="start"]').isDisabled(),true);assert.equal(await page.locator('[data-sentinel-action="pause"]').isDisabled(),true);assert.doesNotMatch(await signal().innerText(),/Gatilho confirmado/);});
test('start shows progress and only acknowledges the state returned by the Agent',async()=>{await page.evaluate(()=>{window.__sentinelOverlayAction=async()=>{await new Promise(r=>setTimeout(r,140));return{ok:true,state:'running',message:'Bot iniciado pelo Agent'}}});await render({state:'stopped'});await page.locator('[data-sentinel-action="start"]').click();assert.match(await page.locator('[data-sentinel-control-msg]').innerText(),/Iniciando bot/);assert.equal(await page.locator('[data-sentinel-action="start"]').isDisabled(),true);await page.getByText('Bot iniciado pelo Agent',{exact:true}).waitFor();assert.match(await page.locator('[data-sentinel-action="start"]').innerText(),/Bot iniciado/);});
test('a missing command connection produces an error instead of an applied confirmation',async()=>{await page.evaluate(()=>{window.__sentinelOverlayAction=undefined});await render({state:'stopped'});await page.locator('[data-sentinel-action="start"]').click();await page.getByText(/Erro: Agent sem conexão/).waitFor();assert.match(await page.locator('[data-sentinel-role="bot-status"]').innerText(),/bot parado/);});
test('expiry and active selection inside a broker subdomain frame are inspected',async()=>{await page.route('https://trade.iqoption.com/fixture',r=>r.fulfill({contentType:'text/html',body:'<button role="tab" aria-selected="true">XAU/USD</button><div class="duration-field" style="width:100px;height:40px">1 min</div>'}));await page.setContent('<html><body><iframe src="https://trade.iqoption.com/fixture" style="width:600px;height:300px"></iframe></body></html>');await page.frameLocator('iframe').getByRole('tab').waitFor();await driver.domSnapshot('iq_option',{fast:true});assert.equal(driver.state('iq_option').uiSymbol,'XAU/USD');await driver.scanExecutionUi('iq_option');assert.equal(driver.state('iq_option').expirationDurationMs,60000);assert.equal(driver.state('iq_option').executionUi.buy,false);await page.unroute('https://trade.iqoption.com/fixture');});

test('broker-page candle responses are correlated without borrowing another open tab',()=>{
 const st=driver.state('iq_option');st.activeId=2114;st.candleSize=60;st.uiSymbol=st.symbol='GBP/CAD OTC';st.uiSymbolSource='view-active';st.candles=[];st.quote=null;
 driver.ingest('iq_option',{name:'sendMessage',request_id:'visible-page-history',msg:{name:'get-candles',body:{active_id:2114,size:60}}},'page-out');
 driver.ingest('iq_option',{name:'candles',request_id:'visible-page-history',msg:{candles:[{from:100,to:160,open:1.8,close:1.81,max:1.82,min:1.79}]}},'page-in');assert.equal(st.quote,1.81);assert.equal(st.candles.length,1);
 driver.ingest('iq_option',{name:'sendMessage',request_id:'background-history',msg:{name:'get-candles',body:{active_id:1912,size:60}}},'page-out');
 driver.ingest('iq_option',{name:'candles',request_id:'background-history',msg:{candles:[{from:100,to:160,open:4137,close:4138,max:4139,min:4136}]}},'page-in');assert.equal(st.quote,1.81);assert.equal(st.candles.length,1);
});
test('prices from the visible asset refresh even when another candle interval streams',()=>{
 const st=driver.state('iq_option');st.activeId=2114;st.candleSize=60;st.candles=[{from:100,to:160,open:1.8,close:1.81,high:1.82,low:1.79}];
 driver.ingest('iq_option',{name:'candle-generated',msg:{active_id:2114,size:5,from:160,to:165,open:1.81,close:1.815,max:1.82,min:1.81}},'page-in');assert.equal(st.quote,1.815);assert.equal(st.candleSize,60);assert.equal(st.candles.length,1);
});
test('technical percentages remain visible through a late price without showing an entry',async()=>{
 await page.setContent('<html><body>Broker</body></html>');await render({liveAgeMs:4800,generalConsensus:{callScore:64,putScore:16},operationalSignal:{...data().operationalSignal,technicalConfidence:64}});const text=await signal().innerText();assert.match(text,/CALL 64%/);assert.match(text,/PUT 16%/);assert.match(text,/64%/);assert.match(text,/ATUALIZANDO PREÇO/);assert.doesNotMatch(text,/\nCALL\n/);assert.doesNotMatch(text,/TEST\/USD/);
});
test('live updates retain card elements, scroll and open analysis instead of rebuilding them',async()=>{
 await page.setContent('<html><body>Broker</body></html>');await render();await page.locator('[data-sentinel-toggle="analysis"]').click();await signal().evaluate(el=>window.__originalSignal=el);await page.locator('[data-sentinel-role="market-reading"]').evaluate(el=>window.__originalReading=el);await page.locator('#sentinel-trading-overlay').evaluate(el=>el.scrollTop=160);
 for(let i=0;i<12;i++)await render({analysisAgeMs:i,confidence:70+i});assert.equal(await signal().evaluate(el=>el===window.__originalSignal),true);assert.equal(await page.locator('[data-sentinel-role="market-reading"]').evaluate(el=>el===window.__originalReading),true);assert.equal(await page.locator('#sentinel-trading-overlay').evaluate(el=>el.scrollTop),160);
});
