import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {LocalPlaywrightDriver} from '../worker/local-playwright-driver.mjs';
import {SentinelRemoteRelay} from '../worker/remote-relay.mjs';
import {DemoTradingRuntime} from '../src/core/runtime.mjs';
const {chromium}=await import(process.env.SENTINEL_TEST_PLAYWRIGHT_MODULE||'playwright');
const folder=await mkdtemp(join(tmpdir(),'sentinel-pipeline-'));
for(const [key,file] of [['SENTINEL_STATE_FILE','state.json'],['SENTINEL_SESSION_VAULT_FILE','vault.json'],['SENTINEL_LOCAL_SECRET_FILE','secret']])process.env[key]=join(folder,file);
process.env.SENTINEL_WORKER_PORT=String(20000+process.pid%15000);
const browser=await chromium.launch({headless:true,...(process.env.SENTINEL_TEST_BROWSER_PATH?{executablePath:process.env.SENTINEL_TEST_BROWSER_PATH}:{})}),page=await browser.newPage({viewport:{width:1280,height:900}});
page.on('pageerror',e=>console.error('PAGE ERROR',e.message));
await page.setContent('<html><body><button role="tab" aria-selected="true">Gold Blitz</button></body></html>');
const raw=new DemoTradingRuntime().feed.snapshot().candles;const candles=raw.map((c,i)=>({...c,from:Math.floor(Date.now()/1000)-(raw.length-i)*60,to:Math.floor(Date.now()/1000)-(raw.length-i-1)*60}));
const original=LocalPlaywrightDriver.prototype.updateOverlay,frames=[];
LocalPlaywrightDriver.prototype.session=async()=>({page,context:page.context(),background:false});
LocalPlaywrightDriver.prototype.sessionInfo=async()=>({open:true,sessionPresent:true,url:'https://iqoption.com/traderoom'});
LocalPlaywrightDriver.prototype.maintain=async function(provider){await this.installBridge(page,provider);const s=this.state(provider);Object.assign(s,{mode:'demo',balance:20000,activeId:1912,symbol:'XAU/USD',uiSymbol:'XAU/USD',uiSymbolSource:'view-active',assetDetection:{confirmed:true},quote:candles.at(-1).close+frames.length*.001,candles,lastQuoteAt:Date.now(),lastCandleAt:Date.now(),protocol:'fixture'});s.assets.add('XAU/USD');s.activeMap.set('XAUUSD',1912);return this.liveStatus(provider)};
LocalPlaywrightDriver.prototype.call=async function(provider,action){await this.maintain(provider);if(action==='resume-visible')return{open:true,sessionPresent:true};if(action==='account')return{mode:'demo'};if(action==='balance')return{balance:20000};if(action==='assets')return['XAU/USD'];if(action==='market-snapshot')return this.liveStatus(provider);if(action.startsWith('quote'))return{price:this.state(provider).quote};if(action.startsWith('candles'))return candles;return{ok:true}};
LocalPlaywrightDriver.prototype.updateOverlay=async function(provider,data){frames.push(data);if(frames.length<7)console.log('FRAME',JSON.stringify({state:data.state,quote:data.quote,age:data.liveAgeMs,stale:data.analysisStale,confirmed:data.assetConfirmed}));return original.call(this,provider,data)};
SentinelRemoteRelay.prototype.init=async function(){this.info.paired=false;return this.info};
SentinelRemoteRelay.prototype.register=async()=>null;SentinelRemoteRelay.prototype.heartbeat=async()=>null;SentinelRemoteRelay.prototype.poll=async()=>null;
await import('../worker/index.mjs');
await page.locator('[data-sentinel-action="start"]').waitFor({timeout:7000});
console.log('START BUTTON',await page.locator('[data-sentinel-action="start"]').innerText());await page.locator('[data-sentinel-action="start"]').click({timeout:6000});console.log('CLICKED START');
console.log('STARTED PANEL',await page.locator('#sentinel-trading-overlay').innerText());await page.getByText('Bot online · aguardando a leitura do ativo',{exact:true}).waitFor();
await page.waitForFunction(()=>{const s=document.getElementById('sentinel-trading-overlay-host')?.shadowRoot?.querySelector('[data-sentinel-role="main-signal"]');return s&&/CALL \d+%/.test(s.textContent)&&!/AGUARDANDO DADOS|SINCRONIZANDO|LENDO GRÁFICO/.test(s.textContent)},null,{timeout:8000});
const frame=frames.filter(f=>f.state==='running').at(-1);assert.ok(frame.quote>0);assert.ok(frame.liveAgeMs>=0&&frame.liveAgeMs<2500);assert.equal(frame.assetConfirmed,true);assert.equal(frame.analysisStale,false);assert.ok(frame.analysisAt>0);assert.equal(frame.brokerConnected,true);
await page.locator('[data-sentinel-action="pause"]').click();await page.getByText('Bot pausado',{exact:true}).waitFor();await page.waitForFunction(()=>document.getElementById('sentinel-trading-overlay-host').shadowRoot.querySelector('[data-sentinel-role="main-signal"]').textContent.includes('PAUSADO'));
await browser.close();await rm(folder,{recursive:true,force:true});console.log('WORKER → LIVE SNAPSHOT → REAL OVERLAY: PASS');process.exit(0);
