import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,readFile,rm,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
const manager=resolve('sentinel-trading-lab/agent/worker/agent-manager.mjs');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const s=http.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p}
async function until(fn){for(let i=0;i<100;i++){try{const r=await fn();if(r)return r}catch{}await delay(50)}throw Error('timeout')}
async function fixture(t,{foreign=false}={}){const root=await mkdtemp(join(tmpdir(),'sentinel-manager-'));await mkdir(join(root,'worker'),{recursive:true});await copyFile(manager,join(root,'worker','agent-manager.mjs'));await writeFile(join(root,'worker','index.mjs'),`import http from 'node:http';import {appendFileSync} from 'node:fs';appendFileSync('spawned','1');http.createServer((q,r)=>{r.setHeader('content-type','application/json');r.end(JSON.stringify({ok:true,version:'13.4.10',build:'13.4.10-independent-1008',pid:process.pid}))}).listen(Number(process.env.SENTINEL_WORKER_PORT),'127.0.0.1');`);const mp=await port(),wp=await port();let old;if(foreign){old=http.createServer((q,r)=>{r.setHeader('content-type','application/json');r.end(JSON.stringify({ok:true,version:'13.4.6',pid:1}))});await new Promise(r=>old.listen(wp,'127.0.0.1',r))}const env={...process.env,SENTINEL_MANAGER_PORT:String(mp),SENTINEL_WORKER_PORT:String(wp)};const child=spawn(process.execPath,[join(root,'worker','agent-manager.mjs')],{cwd:root,env,stdio:'ignore'});const health=()=>fetch(`http://127.0.0.1:${mp}/health`).then(r=>r.json());t.after(async()=>{await fetch(`http://127.0.0.1:${mp}/exit`,{method:'POST'}).catch(()=>{});await delay(500);child.kill();if(old)await new Promise(r=>old.close(r));await rm(root,{recursive:true,force:true})});await until(health);return {root,child,mp,health,env}}
test('manager rejects an older worker on the same port',async t=>{const f=await fixture(t,{foreign:true});const h=await f.health();assert.equal(h.version,'13.4.10');assert.equal(h.workerHealthy,false)});
test('duplicate manager cannot spawn a worker or overwrite the owner PID',async t=>{const f=await fixture(t);await until(async()=>(await f.health()).workerHealthy);const before=await readFile(join(f.root,'worker/data/manager.pid'),'utf8');const duplicate=spawn(process.execPath,[join(f.root,'worker','agent-manager.mjs')],{cwd:f.root,env:f.env,stdio:'ignore'});await new Promise(r=>duplicate.once('exit',r));assert.equal(await readFile(join(f.root,'worker/data/manager.pid'),'utf8'),before);assert.equal(await readFile(join(f.root,'spawned'),'utf8'),'1');assert.equal((await f.health()).workerHealthy,true);await fetch(`http://127.0.0.1:${f.mp}/stop`,{method:'POST'});await delay(1600);assert.equal(await readFile(join(f.root,'spawned'),'utf8'),'1');assert.equal((await f.health()).workerEnabled,false)});
