'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
type Card={id:string;name:string;limit_minor:number|null;closing_day:number|null;due_day:number|null};
type Installment={id:string;amount_minor:number;billing_month:string;paid_at:string|null;card_purchases:{description:string|null;card_id:string}|null};
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const minor=(v:string)=>Math.round((Number(v.replace(/\./g,'').replace(',','.'))||0)*100);
const monthStart=()=>new Date().toISOString().slice(0,7)+'-01';
export function CardManager(){const[cards,setCards]=useState<Card[]>([]);const[installments,setInstallments]=useState<Installment[]>([]);const[openCard,setOpenCard]=useState(false);const[openPurchase,setOpenPurchase]=useState(false);const[name,setName]=useState('');const[limit,setLimit]=useState('');const[closing,setClosing]=useState('');const[due,setDue]=useState('');const[cardId,setCardId]=useState('');const[desc,setDesc]=useState('');const[total,setTotal]=useState('');const[count,setCount]=useState('1');const[notice,setNotice]=useState('');
async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const [{data:c},{data:i}]=await Promise.all([s.from('credit_cards').select('id,name,limit_minor,closing_day,due_day').eq('user_id',user.id).eq('is_active',true).order('created_at'),s.from('card_installments').select('id,amount_minor,billing_month,paid_at,card_purchases(description,card_id)').eq('user_id',user.id).eq('billing_month',monthStart()).order('billing_month')]);setCards((c||[]) as Card[]);setInstallments((i||[]) as unknown as Installment[]);if(!cardId&&c?.[0])setCardId(c[0].id)}
useEffect(()=>{load()},[]);
const billByCard=useMemo(()=>Object.fromEntries(cards.map(card=>[card.id,installments.filter(i=>i.card_purchases?.card_id===card.id).reduce((a,b)=>a+Number(b.amount_minor),0)])),[cards,installments]);
async function addCard(e:FormEvent){e.preventDefault();const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from('credit_cards').insert({user_id:user.id,name,limit_minor:limit?minor(limit):null,closing_day:closing?Number(closing):null,due_day:due?Number(due):null});if(error){setNotice('Não foi possível salvar o cartão.');return}setName('');setLimit('');setClosing('');setDue('');setOpenCard(false);await load()}
async function addPurchase(e:FormEvent){e.preventDefault();const s=createClient();const {error}=await s.rpc('create_card_purchase',{p_card_id:cardId,p_category_id:'card_purchase',p_description:desc,p_total_minor:minor(total),p_purchased_on:new Date().toISOString().slice(0,10),p_installment_count:Number(count),p_is_avoidable:false});if(error){setNotice('Não foi possível salvar a compra.');return}setDesc('');setTotal('');setCount('1');setOpenPurchase(false);await load()}
async function settle(id:string){const s=createClient();const {error}=await s.rpc('settle_card_bill',{p_card_id:id,p_statement_month:monthStart(),p_paid_on:new Date().toISOString().slice(0,10)});if(error){setNotice('Não foi possível marcar a fatura como paga.');return}setNotice('Fatura marcada como paga sem criar uma nova despesa.');await load()}
return <><div className="toolbar"><button className="primary" onClick={()=>setOpenCard(v=>!v)}>+ Adicionar cartão</button>{cards.length>0&&<button className="secondary" onClick={()=>setOpenPurchase(v=>!v)}>+ Registrar compra</button>}</div>{openCard&&<form className="entryForm" onSubmit={addCard}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nubank"/></label><label>Limite<input value={limit} onChange={e=>setLimit(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><label>Dia de fechamento<input value={closing} onChange={e=>setClosing(e.target.value)} inputMode="numeric" min="1" max="31"/></label><label>Dia de vencimento<input value={due} onChange={e=>setDue(e.target.value)} inputMode="numeric" min="1" max="31"/></label><button className="primary">Salvar cartão</button></form>}{openPurchase&&<form className="entryForm" onSubmit={addPurchase}><label>Cartão<select required value={cardId} onChange={e=>setCardId(e.target.value)}>{cards.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Descrição<input required value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Ex.: notebook"/></label><label>Valor total<input required value={total} onChange={e=>setTotal(e.target.value)} inputMode="decimal" placeholder="0,00"/></label><label>Parcelas<input required type="number" min="1" max="60" value={count} onChange={e=>setCount(e.target.value)}/></label><button className="primary">Salvar compra</button></form>}{notice&&<div className="authMessage">{notice}</div>}<section className="cardList">{cards.length===0?<div className="empty"><b>Nenhum cartão cadastrado</b><p>Adicione um cartão para acompanhar fatura e parcelas.</p></div>:cards.map(card=>{const bill=Number(billByCard[card.id]||0);const paid=installments.filter(i=>i.card_purchases?.card_id===card.id).every(i=>i.paid_at);return <article className="creditCard" key={card.id}><div><small>CARTÃO</small><h3>{card.name}</h3><span>Limite {card.limit_minor?brl(card.limit_minor):'não informado'}</span></div><div className="billBox"><small>Fatura do mês</small><strong>{brl(bill)}</strong><span>{card.due_day?'Vence dia '+card.due_day:'Vencimento não informado'}</span>{bill>0&&<button onClick={()=>settle(card.id)} disabled={paid}>{paid?'Fatura paga':'Marcar fatura paga'}</button>}</div></article>})}</section></>}
