'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {localDateISO,localMonthStartISO} from '@/lib/date';
import {categoryOptions,CustomCategory} from '@/domain/categories';

type Card={id:string;name:string;limit_minor:number|null;closing_day:number|null;due_day:number|null};
type Installment={id:string;amount_minor:number;billing_month:string;paid_at:string|null;card_purchases:{description:string|null;card_id:string;is_avoidable:boolean}|null};
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const minor=(v:string)=>Math.round((Number(v.replace(/\./g,'').replace(',','.'))||0)*100);

export function CardManager({onNavigate}:{onNavigate?:(target:string)=>void}){
  const[cards,setCards]=useState<Card[]>([]);const[installments,setInstallments]=useState<Installment[]>([]);const[customCategories,setCustomCategories]=useState<CustomCategory[]>([]);const[openCard,setOpenCard]=useState(false);const[openPurchase,setOpenPurchase]=useState(false);const[name,setName]=useState('');const[limit,setLimit]=useState('');const[closing,setClosing]=useState('');const[due,setDue]=useState('');const[cardId,setCardId]=useState('');const[desc,setDesc]=useState('');const[total,setTotal]=useState('');const[count,setCount]=useState('1');const[category,setCategory]=useState('other');const[avoidable,setAvoidable]=useState(false);const[purchaseDate,setPurchaseDate]=useState(localDateISO());const[notice,setNotice]=useState('');
  const categories=categoryOptions('expense',customCategories);

  async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const month=localMonthStartISO();const[{data:c},{data:i},{data:custom}]=await Promise.all([s.from('credit_cards').select('id,name,limit_minor,closing_day,due_day').eq('user_id',user.id).eq('is_active',true).order('created_at'),s.from('card_installments').select('id,amount_minor,billing_month,paid_at,card_purchases(description,card_id,is_avoidable)').eq('user_id',user.id).gte('billing_month',month).order('billing_month'),s.from('finance_categories').select('id,kind,name,icon,show_in_quick,is_active').eq('user_id',user.id).eq('kind','expense').order('created_at')]);setCards((c||[]) as Card[]);setInstallments((i||[]) as unknown as Installment[]);setCustomCategories((custom||[]) as CustomCategory[]);if(!cardId&&c?.[0])setCardId(c[0].id)}
  useEffect(()=>{load();const refresh=()=>load();window.addEventListener('devinx:categories-updated',refresh);return()=>window.removeEventListener('devinx:categories-updated',refresh)},[]);

  const currentMonth=localMonthStartISO();
  const stats=useMemo(()=>Object.fromEntries(cards.map(card=>{const rows=installments.filter(i=>i.card_purchases?.card_id===card.id);const current=rows.filter(i=>i.billing_month===currentMonth);const currentOpen=current.filter(i=>!i.paid_at).reduce((a,b)=>a+Number(b.amount_minor),0);const currentPaid=current.filter(i=>i.paid_at).reduce((a,b)=>a+Number(b.amount_minor),0);const future=rows.filter(i=>i.billing_month>currentMonth&&!i.paid_at).reduce((a,b)=>a+Number(b.amount_minor),0);return[card.id,{currentOpen,currentPaid,future,totalOpen:currentOpen+future,currentRows:current}]})),[cards,installments,currentMonth]);

  async function addCard(e:FormEvent){e.preventDefault();const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from('credit_cards').insert({user_id:user.id,name:name.trim(),limit_minor:limit?minor(limit):null,closing_day:closing?Number(closing):null,due_day:due?Number(due):null});if(error){setNotice('Não foi possível salvar o cartão.');return}setName('');setLimit('');setClosing('');setDue('');setOpenCard(false);setNotice('');await load()}
  async function addPurchase(e:FormEvent){e.preventDefault();const value=minor(total);if(value<=0){setNotice('Informe o valor total.');return}const s=createClient();const{error}=await s.rpc('create_card_purchase',{p_card_id:cardId,p_category_id:category,p_description:desc.trim()||null,p_total_minor:value,p_purchased_on:purchaseDate,p_installment_count:Number(count),p_is_avoidable:avoidable});if(error){setNotice('Não foi possível salvar as parcelas.');return}setDesc('');setTotal('');setCount('1');setCategory('other');setAvoidable(false);setPurchaseDate(localDateISO());setOpenPurchase(false);setNotice('Parcelas distribuídas nos meses corretos.');window.dispatchEvent(new CustomEvent('devinx:finance-updated'));await load()}
  async function settle(id:string){const s=createClient();const{error}=await s.rpc('settle_card_bill',{p_card_id:id,p_statement_month:localMonthStartISO(),p_paid_on:localDateISO()});if(error){setNotice('Não foi possível marcar a fatura como paga.');return}setNotice('Fatura quitada sem duplicar a despesa.');window.dispatchEvent(new CustomEvent('devinx:finance-updated'));await load()}

  return <>
    <section className="moduleSummary cardDebtIntro"><small>CARTÃO É COMPROMISSO MENSAL</small><strong>Veja o que vence agora e o que ainda falta pagar.</strong><span>Cadastre o cartão uma vez. Depois informe a dívida/compra e as parcelas; o Devinx distribui automaticamente por mês.</span></section>
    <div className="toolbar"><button className="secondary" onClick={()=>setOpenCard(v=>!v)}>{openCard?'Fechar cadastro':'+ Cartão'}</button>{cards.length>0&&<button className="primary" onClick={()=>setOpenPurchase(v=>!v)}>{openPurchase?'Fechar':'＋ Adicionar dívida/parcelas'}</button>}{onNavigate&&<button className="secondary" type="button" onClick={()=>onNavigate('categories')}>Categorias</button>}</div>
    {openCard&&<form className="entryForm" onSubmit={addCard}><label>Nome do cartão<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nubank"/></label><label>Dia de fechamento<input value={closing} onChange={e=>setClosing(e.target.value)} inputMode="numeric" min="1" max="31" placeholder="Ex.: 5"/></label><label>Dia de vencimento<input value={due} onChange={e=>setDue(e.target.value)} inputMode="numeric" min="1" max="31" placeholder="Ex.: 12"/></label><label>Limite <small>(opcional)</small><input value={limit} onChange={e=>setLimit(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><button className="primary">Salvar cartão</button></form>}
    {openPurchase&&<form className="entryForm" onSubmit={addPurchase}><label>Cartão<select required value={cardId} onChange={e=>setCardId(e.target.value)}>{cards.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>O que você deve?<input required value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Ex.: celular, pneus, compra do mês"/></label><label>Valor total<input required value={total} onChange={e=>setTotal(e.target.value)} inputMode="decimal" placeholder="0,00"/></label><label>Parcelas<input required type="number" min="1" max="60" value={count} onChange={e=>setCount(e.target.value)}/></label><label>Data da compra<input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)} required/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(item=><option value={item.id} key={item.id}>{item.icon} {item.name}</option>)}</select></label><label className="checkOnly"><input type="checkbox" checked={avoidable} onChange={e=>setAvoidable(e.target.checked)}/> É um gasto evitável</label><button className="primary">Distribuir parcelas</button></form>}
    {notice&&<div className="authMessage">{notice}</div>}
    <section className="cardList">{cards.length===0?<div className="empty"><b>Nenhum cartão ainda</b><p>Cadastre apenas o cartão que realmente usa. Depois informe as dívidas parceladas.</p></div>:cards.map(card=>{const s=stats[card.id]||{currentOpen:0,currentPaid:0,future:0,totalOpen:0,currentRows:[]};return <article className="creditCard creditCardDebt" key={card.id}><div className="cardIdentity"><small>CARTÃO</small><h3>{card.name}</h3><span>{card.due_day?'Vence dia '+card.due_day:'Vencimento não informado'}{card.closing_day?' · fecha dia '+card.closing_day:''}</span>{card.limit_minor!=null&&<span>Limite {brl(Number(card.limit_minor))}</span>}</div><div className="cardDebtNumbers"><div><small>Este mês</small><strong>{brl(s.currentOpen)}</strong></div><div><small>Próximos meses</small><strong>{brl(s.future)}</strong></div><div className="cardTotalOpen"><small>Total ainda comprometido</small><strong>{brl(s.totalOpen)}</strong></div>{s.currentPaid>0&&<span className="paidNote">Pago neste mês: {brl(s.currentPaid)}</span>}{s.currentOpen>0&&<button onClick={()=>settle(card.id)}>Marcar fatura deste mês como paga</button>}</div></article>})}</section>
  </>;
}
