'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Kind='income'|'expense';
type Item={id:string;description:string|null;amount_minor:number;occurred_on:string;category_id:string;is_avoidable:boolean;is_recurring:boolean};

const expenseCategories=[['housing','Moradia'],['food','Alimentação'],['transport','Transporte'],['health','Saúde'],['education','Educação'],['subscriptions','Assinaturas'],['leisure','Lazer'],['other','Outros']];
const incomeCategories=[['salary','Salário'],['driver','Corridas'],['delivery','Entregas'],['commission','Comissão'],['extra','Renda extra'],['other','Outros']];

function money(minor:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(minor/100)}
function toMinor(raw:string){const normalized=raw.replace(/\./g,'').replace(',','.').replace(/[^0-9.]/g,'');return Math.round((Number(normalized)||0)*100)}

export function TransactionManager({kind}:{kind:Kind}){
  const [open,setOpen]=useState(false);const [amount,setAmount]=useState('');const [description,setDescription]=useState('');const [category,setCategory]=useState(kind==='income'?'salary':'food');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [payment,setPayment]=useState('pix');const [avoidable,setAvoidable]=useState(false);const [recurring,setRecurring]=useState(false);const [items,setItems]=useState<Item[]>([]);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');
  const categories=kind==='income'?incomeCategories:expenseCategories;
  const total=useMemo(()=>items.reduce((sum,item)=>sum+Number(item.amount_minor),0),[items]);

  async function load(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('transactions').select('id,description,amount_minor,occurred_on,category_id,is_avoidable,is_recurring').eq('user_id',user.id).eq('type',kind).order('occurred_on',{ascending:false}).limit(30);setItems((data||[]) as Item[])}
  useEffect(()=>{load()},[kind]);

  async function submit(e:FormEvent){e.preventDefault();const amountMinor=toMinor(amount);if(amountMinor<=0){setNotice('Informe um valor maior que zero.');return}setSaving(true);setNotice('');const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/entrar';return}const {error}=await supabase.from('transactions').insert({user_id:user.id,type:kind,category_id:category,description:description.trim()||null,amount_minor:amountMinor,occurred_on:date,payment_method:kind==='expense'?payment:null,is_avoidable:kind==='expense'?avoidable:false,is_recurring:kind==='expense'?recurring:false});setSaving(false);if(error){setNotice('Não foi possível salvar. Tente novamente.');return}setAmount('');setDescription('');setOpen(false);await load()}

  return <><section className="moduleSummary"><small>{kind==='income'?'TOTAL DE ENTRADAS':'TOTAL DE GASTOS'}</small><strong>{money(total)}</strong><span>últimos lançamentos carregados</span></section><button className="primary" onClick={()=>setOpen(!open)}>{open?'Fechar':kind==='income'?'+ Nova entrada':'+ Novo gasto'}</button>{open&&<form className="entryForm" onSubmit={submit}><label>Valor<input required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><label>Descrição<input value={description} onChange={e=>setDescription(e.target.value)} placeholder={kind==='income'?'Ex.: salário, corrida, comissão':'Ex.: mercado, aluguel, almoço'}/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label>{kind==='expense'&&<><label>Pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="debit">Débito</option><option value="credit">Crédito</option></select></label><div className="checkRow"><label><input type="checkbox" checked={avoidable} onChange={e=>setAvoidable(e.target.checked)}/> Gasto evitável</label><label><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Recorrente</label></div></>}<button className="primary" disabled={saving}>{saving?'Salvando...':'Salvar'}</button>{notice&&<div className="authMessage">{notice}</div>}</form>}<section className="transactionList">{items.length===0?<div className="empty"><b>Nenhum lançamento ainda</b><p>O primeiro lançamento aparecerá aqui.</p></div>:items.map(item=><article key={item.id}><div><b>{item.description||categories.find(c=>c[0]===item.category_id)?.[1]||'Lançamento'}</b><small>{new Date(item.occurred_on+'T12:00:00').toLocaleDateString('pt-BR')}{item.is_avoidable?' · evitável':''}{item.is_recurring?' · recorrente':''}</small></div><strong className={kind==='income'?'positive':'negative'}>{kind==='income'?'+ ':'- '}{money(Number(item.amount_minor))}</strong></article>)}</section></>}
