'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Vehicle={id:string;name:string;energy_type:string;efficiency:number|null;unit_price_minor:number|null};
type Session={gross_income_minor:number;energy_cost_minor:number;extra_work_cost_minor:number;distance_km:number;minutes_worked:number};
function minor(raw:string){return Math.round((Number(raw.replace(',','.'))||0)*100)}
function brl(v:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100)}

export function WorkManager(){
  const [vehicle,setVehicle]=useState<Vehicle|null>(null);const [sessions,setSessions]=useState<Session[]>([]);const [name,setName]=useState('Meu veículo');const [energy,setEnergy]=useState('gasoline');const [efficiency,setEfficiency]=useState('10');const [unitPrice,setUnitPrice]=useState('6');const [gross,setGross]=useState('');const [km,setKm]=useState('');const [hours,setHours]=useState('');const [extra,setExtra]=useState('0');const [notice,setNotice]=useState('');
  async function load(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/entrar';return}const [v,s]=await Promise.all([supabase.from('vehicles').select('id,name,energy_type,efficiency,unit_price_minor').eq('user_id',user.id).eq('is_default',true).limit(1),supabase.from('work_sessions').select('gross_income_minor,energy_cost_minor,extra_work_cost_minor,distance_km,minutes_worked').eq('user_id',user.id).order('worked_on',{ascending:false}).limit(30)]);setVehicle((v.data?.[0] as Vehicle)||null);setSessions((s.data||[]) as Session[])}
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>{const gross=sessions.reduce((a,b)=>a+Number(b.gross_income_minor),0);const energyCost=sessions.reduce((a,b)=>a+Number(b.energy_cost_minor),0);const extraCost=sessions.reduce((a,b)=>a+Number(b.extra_work_cost_minor),0);const distance=sessions.reduce((a,b)=>a+Number(b.distance_km),0);const h=sessions.reduce((a,b)=>a+Number(b.minutes_worked),0)/60;const operationalCost=energyCost+extraCost;const net=gross-operationalCost;return{gross,energyCost,extraCost,operationalCost,distance,h,net,perHour:h>0?net/h:0,perKm:distance>0?net/distance:0}},[sessions]);
  async function saveVehicle(e:FormEvent){e.preventDefault();const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('vehicles').update({is_default:false}).eq('user_id',user.id).eq('is_default',true);const {error}=await supabase.from('vehicles').insert({user_id:user.id,name,energy_type:energy,efficiency:energy==='human'?null:Number(efficiency),unit_price_minor:energy==='human'?0:minor(unitPrice),is_default:true});if(error){setNotice('Não foi possível salvar o veículo.');return}setNotice('Veículo salvo.');await load()}
  async function saveSession(e:FormEvent){e.preventDefault();if(!vehicle){setNotice('Configure seu veículo primeiro.');return}const distance=Number(km.replace(',','.'))||0;const workedHours=Number(hours.replace(',','.'))||0;const efficiencyValue=Number(vehicle.efficiency)||0;const energyCost=vehicle.energy_type==='human'?0:efficiencyValue>0?Math.round((distance/efficiencyValue)*Number(vehicle.unit_price_minor||0)):0;const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('work_sessions').insert({user_id:user.id,vehicle_id:vehicle.id,worked_on:new Date().toISOString().slice(0,10),gross_income_minor:minor(gross),energy_cost_minor:energyCost,extra_work_cost_minor:minor(extra),distance_km:distance,minutes_worked:Math.round(workedHours*60)});if(error){setNotice('Não foi possível salvar a jornada.');return}setGross('');setKm('');setHours('');setExtra('0');setNotice('Jornada registrada.');await load()}
  return <>{!vehicle?<section className="panel"><h2>Configure seu veículo</h2><p className="lead">Isso é feito uma vez. O Devinx calcula combustível ou energia automaticamente.</p><form className="entryForm" onSubmit={saveVehicle}><label>Nome<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select value={energy} onChange={e=>setEnergy(e.target.value)}><option value="gasoline">Gasolina</option><option value="ethanol">Etanol</option><option value="diesel">Diesel</option><option value="hybrid">Híbrido</option><option value="electric">Elétrico</option><option value="human">Bicicleta</option></select></label>{energy!=='human'&&<><label>{energy==='electric'?'Km por kWh':'Km por litro'}<input value={efficiency} onChange={e=>setEfficiency(e.target.value)} inputMode="decimal"/></label><label>{energy==='electric'?'Preço do kWh':'Preço por litro'}<input value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} inputMode="decimal"/></label></>}<button className="primary">Salvar veículo</button></form></section>:<><div className="metricGrid"><article><small>Líquido / hora</small><b>{stats.h?brl(Math.round(stats.perHour)):'—'}</b></article><article><small>Líquido / km</small><b>{stats.distance?brl(Math.round(stats.perKm)):'—'}</b></article><article><small>Combustível / energia</small><b>{brl(stats.energyCost)}</b></article><article><small>Líquido operacional</small><b>{brl(stats.net)}</b></article></div><section className="panel"><h2>Registrar jornada</h2><p className="lead">Veículo: {vehicle.name}</p><form className="entryForm" onSubmit={saveSession}><label>Ganhos<input required value={gross} onChange={e=>setGross(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><label>Quilômetros<input required value={km} onChange={e=>setKm(e.target.value)} placeholder="0" inputMode="decimal"/></label><label>Horas trabalhadas<input required value={hours} onChange={e=>setHours(e.target.value)} placeholder="0" inputMode="decimal"/></label><label>Outros custos do trabalho<input value={extra} onChange={e=>setExtra(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><button className="primary">Salvar jornada</button></form></section><section className="note">Almoço, mercado, aluguel e outros gastos pessoais não entram no cálculo da produtividade. Só combustível/energia e custos operacionais do trabalho.</section></>}{notice&&<div className="authMessage">{notice}</div>}</>}
