'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {hoursToGoal} from '@/domain/finance';

type Vehicle={id:string;name:string;vehicle_type:'car'|'motorcycle'|'bicycle';energy_type:string;efficiency:number|null;unit_price_minor:number|null};
type Source={id:string;name:string;kind:'driver'|'delivery'};
type Session={gross_income_minor:number;energy_cost_minor:number;extra_work_cost_minor:number;distance_km:number;minutes_worked:number;worked_on:string;income_source_id:string|null};
type Goal={name:string;target_minor:number;basis:string;period:string};
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const minor=(raw:string)=>Math.round((Number(raw.replace(/\./g,'').replace(',','.'))||0)*100);
const decimal=(raw:string)=>Number(raw.replace(',','.'))||0;
const isoDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function periodStart(period:string){const d=new Date();if(period==='daily')return isoDate(d);if(period==='weekly'){const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return isoDate(d)}d.setDate(1);return isoDate(d)}
const vehicleLabel=(type:string)=>type==='motorcycle'?'Moto':type==='bicycle'?'Bicicleta':'Carro';
const energyLabel=(type:string)=>({gasoline:'Gasolina',ethanol:'Etanol',diesel:'Diesel',hybrid:'Híbrido',electric:'Elétrico',human:'Sem combustível'}[type]||type);

export function WorkManager(){
  const[vehicle,setVehicle]=useState<Vehicle|null>(null);const[editingVehicle,setEditingVehicle]=useState(false);const[sources,setSources]=useState<Source[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[goal,setGoal]=useState<Goal|null>(null);
  const[name,setName]=useState('Meu veículo');const[vehicleType,setVehicleType]=useState<'car'|'motorcycle'|'bicycle'>('car');const[energy,setEnergy]=useState('gasoline');const[efficiency,setEfficiency]=useState('10');const[unitPrice,setUnitPrice]=useState('6');
  const[sourceId,setSourceId]=useState('');const[newSource,setNewSource]=useState('');const[newSourceKind,setNewSourceKind]=useState<'driver'|'delivery'>('driver');const[gross,setGross]=useState('');const[km,setKm]=useState('');const[energySpent,setEnergySpent]=useState('');const[hours,setHours]=useState('');const[extra,setExtra]=useState('0');const[notice,setNotice]=useState('');

  function fillVehicleForm(v:Vehicle){setName(v.name);setVehicleType(v.vehicle_type||'car');setEnergy(v.energy_type);setEfficiency(v.efficiency==null?'':String(v.efficiency));setUnitPrice(v.unit_price_minor==null?'':String(Number(v.unit_price_minor)/100).replace('.',','))}
  async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const since=new Date();since.setDate(since.getDate()-30);const[v,src,ss,g]=await Promise.all([s.from('vehicles').select('id,name,vehicle_type,energy_type,efficiency,unit_price_minor').eq('user_id',user.id).eq('is_default',true).limit(1),s.from('income_sources').select('id,name,kind').eq('user_id',user.id).in('kind',['driver','delivery']).eq('is_active',true).order('created_at'),s.from('work_sessions').select('gross_income_minor,energy_cost_minor,extra_work_cost_minor,distance_km,minutes_worked,worked_on,income_source_id').eq('user_id',user.id).gte('worked_on',isoDate(since)).order('worked_on',{ascending:false}),s.from('goals').select('name,target_minor,basis,period').eq('user_id',user.id).eq('is_active',true).in('basis',['gross','operational_net']).limit(1)]);const sourceRows=(src.data||[]) as Source[];const loadedVehicle=(v.data?.[0] as Vehicle)||null;setVehicle(loadedVehicle);if(loadedVehicle)fillVehicleForm(loadedVehicle);setSources(sourceRows);setSessions((ss.data||[]) as Session[]);setGoal((g.data?.[0] as Goal)||null);setSourceId(current=>current||sourceRows[0]?.id||'')}
  useEffect(()=>{load()},[]);

  const stats=useMemo(()=>{const grossIncome=sessions.reduce((a,b)=>a+Number(b.gross_income_minor),0);const energyCost=sessions.reduce((a,b)=>a+Number(b.energy_cost_minor),0);const extraCost=sessions.reduce((a,b)=>a+Number(b.extra_work_cost_minor),0);const distance=sessions.reduce((a,b)=>a+Number(b.distance_km),0);const workedHours=sessions.reduce((a,b)=>a+Number(b.minutes_worked),0)/60;const operationalCost=energyCost+extraCost;const net=grossIncome-operationalCost;return{gross:grossIncome,energyCost,extraCost,operationalCost,distance,h:workedHours,net,grossPerHour:workedHours>0?grossIncome/workedHours:0,netPerHour:workedHours>0?net/workedHours:0,perKm:distance>0?net/distance:0}},[sessions]);
  const sourceStats=useMemo(()=>sources.map(source=>{const rows=sessions.filter(s=>s.income_source_id===source.id);const h=rows.reduce((a,b)=>a+Number(b.minutes_worked),0)/60;const grossIncome=rows.reduce((a,b)=>a+Number(b.gross_income_minor),0);const cost=rows.reduce((a,b)=>a+Number(b.energy_cost_minor)+Number(b.extra_work_cost_minor),0);const net=grossIncome-cost;return{id:source.id,name:source.name,h,netPerHour:h>0?net/h:0}}).filter(x=>x.h>0),[sources,sessions]);
  const goalForecast=useMemo(()=>{if(!goal)return null;const start=periodStart(goal.period);const current=sessions.filter(s=>s.worked_on>=start).reduce((sum,s)=>sum+(goal.basis==='gross'?Number(s.gross_income_minor):Number(s.gross_income_minor)-Number(s.energy_cost_minor)-Number(s.extra_work_cost_minor)),0);const remaining=Math.max(0,Number(goal.target_minor)-current);const historyReady=sessions.length>=3&&stats.h>=3;const rate=goal.basis==='gross'?stats.grossPerHour:stats.netPerHour;return{current,remaining,historyReady,hours:historyReady?hoursToGoal(remaining,rate):null}},[goal,sessions,stats]);

  function changeVehicleType(type:'car'|'motorcycle'|'bicycle'){setVehicleType(type);if(type==='bicycle')setEnergy('human');else if(energy==='human')setEnergy('gasoline');if(!vehicle||vehicle.vehicle_type!==type)setName(type==='motorcycle'?'Minha moto':type==='bicycle'?'Minha bicicleta':'Meu carro')}
  async function saveVehicle(e:FormEvent){e.preventDefault();const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const actualEnergy=vehicleType==='bicycle'?'human':energy;const payload={name:name.trim()||'Meu veículo',vehicle_type:vehicleType,energy_type:actualEnergy,efficiency:actualEnergy==='human'?null:decimal(efficiency),unit_price_minor:actualEnergy==='human'?0:minor(unitPrice),is_default:true};let error;if(vehicle){({error}=await s.from('vehicles').update(payload).eq('id',vehicle.id).eq('user_id',user.id))}else{await s.from('vehicles').update({is_default:false}).eq('user_id',user.id).eq('is_default',true);({error}=await s.from('vehicles').insert({user_id:user.id,...payload}))}if(error){setNotice('Não foi possível salvar o veículo.');return}setEditingVehicle(false);setNotice('Veículo configurado. A partir de agora o Devinx usa esses dados automaticamente.');await load()}
  async function addSource(){const value=newSource.trim();if(!value)return;const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from('income_sources').upsert({user_id:user.id,kind:newSourceKind,name:value},{onConflict:'user_id,kind,name',ignoreDuplicates:true});if(error){setNotice('Não foi possível adicionar a fonte.');return}setNewSource('');await load()}

  async function saveSession(e:FormEvent){e.preventDefault();if(!vehicle){setNotice('Configure seu veículo primeiro.');return}const enteredDistance=decimal(km);const workedHours=decimal(hours);if(workedHours<=0){setNotice('Informe as horas trabalhadas.');return}const efficiencyValue=Number(vehicle.efficiency)||0;const unitPrice=Number(vehicle.unit_price_minor)||0;const enteredEnergyCost=minor(energySpent);let distance=enteredDistance;let energyCost=0;
    if(vehicle.energy_type!=='human'){
      if(enteredEnergyCost>0)energyCost=enteredEnergyCost;
      else if(enteredDistance>0&&efficiencyValue>0&&unitPrice>0)energyCost=Math.round((enteredDistance/efficiencyValue)*unitPrice);
      if(distance<=0&&enteredEnergyCost>0&&efficiencyValue>0&&unitPrice>0)distance=(enteredEnergyCost/unitPrice)*efficiencyValue;
    }
    const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from('work_sessions').insert({user_id:user.id,vehicle_id:vehicle.id,income_source_id:sourceId||null,worked_on:isoDate(new Date()),gross_income_minor:minor(gross),energy_cost_minor:energyCost,extra_work_cost_minor:minor(extra),distance_km:Number(distance.toFixed(2)),minutes_worked:Math.round(workedHours*60)});if(error){setNotice('Não foi possível salvar a jornada.');return}setGross('');setKm('');setEnergySpent('');setHours('');setExtra('0');setNotice(distance>0?'Jornada registrada. Distância e custo operacional calculados.':'Jornada registrada. Você pode deixar o KM em branco; o R$/km só aparece quando houver distância ou gasto de combustível/energia suficiente para estimá-la.');await load()}

  const showVehicleForm=!vehicle||editingVehicle;
  return <>
    {showVehicleForm?<section className="panel vehicleSetup"><div className="sectionHeading"><div><small>CONFIGURAÇÃO DE TRABALHO</small><h2>{vehicle?'Editar veículo':'Configure seu veículo uma vez'}</h2></div>{vehicle&&<button type="button" className="textButton" onClick={()=>setEditingVehicle(false)}>Cancelar</button>}</div><p className="lead">Informe o consumo e o preço uma vez. Depois, no dia a dia, você não precisa preencher tudo de novo.</p><form className="entryForm" onSubmit={saveVehicle}><label>Veículo<select value={vehicleType} onChange={e=>changeVehicleType(e.target.value as 'car'|'motorcycle'|'bicycle')}><option value="car">Carro</option><option value="motorcycle">Moto</option><option value="bicycle">Bicicleta</option></select></label><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Meu carro"/></label>{vehicleType!=='bicycle'&&<><label>Combustível / energia<select value={energy} onChange={e=>setEnergy(e.target.value)}><option value="gasoline">Gasolina</option><option value="ethanol">Etanol</option><option value="diesel">Diesel</option><option value="hybrid">Híbrido</option><option value="electric">Elétrico</option></select></label><label>{energy==='electric'?'Km por kWh':'Km por litro'}<input required value={efficiency} onChange={e=>setEfficiency(e.target.value)} inputMode="decimal" placeholder={energy==='electric'?'Ex.: 6,5':'Ex.: 11,5'}/></label><label>{energy==='electric'?'Preço do kWh':'Preço por litro'}<input required value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} inputMode="decimal" placeholder="Ex.: 6,19"/></label></>}<button className="primary">Salvar configuração</button></form></section>:<section className="vehicleSummary"><div><small>SEU VEÍCULO</small><b>{vehicleLabel(vehicle.vehicle_type)} · {vehicle.name}</b><span>{energyLabel(vehicle.energy_type)}{vehicle.energy_type!=='human'&&vehicle.efficiency?` · ${vehicle.efficiency} ${vehicle.energy_type==='electric'?'km/kWh':'km/L'}`:''}{vehicle.energy_type!=='human'&&vehicle.unit_price_minor?` · ${brl(Number(vehicle.unit_price_minor))}/${vehicle.energy_type==='electric'?'kWh':'L'}`:''}</span></div><button type="button" className="secondary" onClick={()=>setEditingVehicle(true)}>Editar</button></section>}

    {vehicle&&!editingVehicle&&<><div className="metricGrid"><article><small>Líquido / hora</small><b>{stats.h?brl(Math.round(stats.netPerHour)):'—'}</b></article><article><small>Líquido / km</small><b>{stats.distance?brl(Math.round(stats.perKm)):'—'}</b></article><article><small>Combustível / energia</small><b>{brl(stats.energyCost)}</b></article><article><small>Líquido operacional</small><b>{brl(stats.net)}</b></article></div>{goal&&goalForecast&&<section className="panel"><h2>{goal.name}</h2><p className="lead">{brl(goalForecast.current)} de {brl(Number(goal.target_minor))} neste período.</p>{goalForecast.remaining===0?<div className="goalForecast good"><b>Meta alcançada</b><span>Você já atingiu essa meta.</span></div>:goalForecast.historyReady&&goalForecast.hours!==null?<div className="goalForecast"><b>Estimativa: {goalForecast.hours.toFixed(1)} h</b><span>Baseada apenas no seu próprio histórico dos últimos 30 dias.</span></div>:<div className="note">Registre pelo menos 3 jornadas e 3 horas de trabalho para o Devinx estimar quanto falta trabalhar sem inventar médias.</div>}</section>}
      <section className="panel"><h2>Registrar jornada</h2><p className="lead">Preencha só o essencial. Quilômetros não são obrigatórios.</p>{sources.length>0&&<label className="standaloneLabel">Fonte de renda<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{sources.map(source=><option value={source.id} key={source.id}>{source.name}</option>)}</select></label>}<form className="entryForm compactWorkForm" onSubmit={saveSession}><label>Ganhos<input required value={gross} onChange={e=>setGross(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><label>Horas trabalhadas<input required value={hours} onChange={e=>setHours(e.target.value)} placeholder="Ex.: 6,5" inputMode="decimal"/></label><label>Quilômetros <small>(opcional)</small><input value={km} onChange={e=>setKm(e.target.value)} placeholder="Se souber, informe" inputMode="decimal"/></label>{vehicle.energy_type!=='human'&&<label>Combustível / energia gasto <small>(opcional)</small><input value={energySpent} onChange={e=>setEnergySpent(e.target.value)} placeholder="Ex.: 80,00" inputMode="decimal"/></label>}<label>Outros custos do trabalho <small>(opcional)</small><input value={extra} onChange={e=>setExtra(e.target.value)} placeholder="0,00" inputMode="decimal"/></label><button className="primary">Salvar jornada</button></form>{vehicle.energy_type!=='human'&&<p className="smartHint">Se informar o KM, calculamos o combustível/energia. Se deixar o KM vazio e informar quanto gastou, estimamos os quilômetros usando {vehicle.energy_type==='electric'?'km/kWh':'km/L'} e o preço cadastrados.</p>}<div className="inlineAdd sourceAdd"><select value={newSourceKind} onChange={e=>setNewSourceKind(e.target.value as 'driver'|'delivery')}><option value="driver">Motorista</option><option value="delivery">Entregador</option></select><input value={newSource} onChange={e=>setNewSource(e.target.value)} placeholder="Adicionar outra fonte"/><button type="button" className="secondary" onClick={addSource}>Adicionar</button></div></section>
      {sourceStats.length>=2&&<section className="panel"><h2>Comparação pelas suas fontes</h2><p className="lead">Somente com os seus próprios registros dos últimos 30 dias.</p><div className="sourceComparison">{sourceStats.map(source=><article key={source.id}><b>{source.name}</b><strong>{brl(Math.round(source.netPerHour))}/h</strong><small>{source.h.toFixed(1)} h registradas</small></article>)}</div></section>}<section className="note">Almoço, mercado, aluguel e outros gastos pessoais não entram no cálculo da produtividade. Só combustível/energia e custos operacionais do trabalho.</section></>}
    {notice&&<div className="authMessage">{notice}</div>}
  </>}
